
package utils;

import org.testng.annotations.Test;

import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.UUID;

/**
 * Utility class for generating random data for testing purposes.
 *
 * <p>This class provides methods for generating random strings, numbers,
 * and various types of fake data using the Faker library.</p>
 *
 * @version 1.0
 * @since 2022
 */
public class DataGenerateUtils {

    private DataGenerateUtils() {
        super();
    }

    private static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    private static SecureRandom random = new SecureRandom();

    /**
     * Generates a random string of the specified length.
     *
     * @param length the length of the random string to generate.
     * @return a random string of the specified length.
     */
    public static String randomString(int length) {
        StringBuilder sb = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            sb.append(AB.charAt(random.nextInt(AB.length())));
        }
        return sb.toString();
    }
    /**
     * Generates a random hexadecimal string of the specified byte length.
     *
     * @param byteLength the length of the byte array.
     * @return a random hexadecimal string.
     */
    public static String randomStringHexToken(int byteLength) {
        SecureRandom secureRandom = new SecureRandom();
        byte[] token = new byte[byteLength];
        secureRandom.nextBytes(token);
        return new BigInteger(1, token).toString(16); // Hexadecimal encoding
    }
    /**
     * Generates a random UUID string.
     *
     * @return a random UUID string.
     */
    public static String randomStringUUID() {
        String uuid = UUID.randomUUID().toString();
        return uuid;
    }
    /**
     * Generates a random integer between the specified range (inclusive).
     *
     * @param from the lower bound of the range.
     * @param to the upper bound of the range.
     * @return a random integer between the specified range.
     */
    public static int randomNumberIntFromTo(int from, int to) {
        int random_int = (int) Math.floor(Math.random() * (to - from + 1) + from);
        return random_int;
    }
    /**
     * Generates a random full name.
     *
     * @return a random full name.
     */
    public static String randomFullName() {
        return DataFakerUtils.getFaker().name().fullName();
    }
    /**
     * Generates a random phone number.
     *
     * @return a random phone number.
     */
    public static String randomPhoneNumber() {
        return DataFakerUtils.getFaker().phoneNumber().phoneNumber();
    }
    /**
     * Generates a random country name.
     *
     * @return a random country name.
     */
    public static String randomCountry() {
        return DataFakerUtils.getFaker().address().country();
    }
    /**
     * Generates a random zip code.
     *
     * @return a random zip code.
     */
    public static String randomZipCode() {
        return DataFakerUtils.getFaker().address().zipCode();
    }
    /**
     * Generates a random full address.
     *
     * @return a random full address.
     */
    public static String randomAddress() {
        return DataFakerUtils.getFaker().address().fullAddress();
    }
    /**
     * Generates a random city name.
     *
     * @return a random city name.
     */
    public static String randomCity() {
        return DataFakerUtils.getFaker().address().cityName();
    }
    /**
     * Generates a random state name.
     *
     * @return a random state name.
     */
    public static String randomState() {
        return DataFakerUtils.getFaker().address().state();
    }
    /**
     * Generates a random street name.
     *
     * @return a random street name.
     */
    public static String randomStreetName() {
        return DataFakerUtils.getFaker().address().streetName();
    }
    /**
     * Generates a random job title.
     *
     * @return a random job title.
     */
    public static String randomJobTitle() {
        return DataFakerUtils.getFaker().job().title();
    }
    /**
     * Generates random job skills.
     *
     * @return random job skills.
     */
    public static String randomJobSkills() {
        return DataFakerUtils.getFaker().job().keySkills();
    }
    /**
     * Generates a random programming language name.
     *
     * @return a random programming language name.
     */
    public static String randomProgrammingLanguage() {
        return DataFakerUtils.getFaker().programmingLanguage().name();
    }

    /**
     * Test method to print random data generated by various methods in this class.
     */

    @Test
    public void testDataGeneration() {
        System.out.println(randomProgrammingLanguage());
        System.out.println(randomJobTitle());
        System.out.println(randomJobSkills());
        System.out.println(randomFullName());
        System.out.println(randomPhoneNumber());
        System.out.println(randomAddress());
        System.out.println(randomCountry());
        System.out.println(randomZipCode());
        System.out.println(randomState());
        System.out.println(randomCity());
        System.out.println(randomStreetName());
    }

}
